# Generated by Django 4.1.1 on 2022-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_business',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='foundation_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
