# Generated by Django 4.1.1 on 2022-09-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0002_alter_company_company_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='foundation_date',
            field=models.DateField(),
        ),
    ]
